# Generated by Django 3.2.15 on 2022-09-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('favorite_car_brand', models.TextField(blank=True)),
                ('profileimage', models.ImageField(default='../default_profile_c4xbsi', upload_to='images/')),
                ('experience', models.CharField(choices=[('no_experience', 'No experience'), ('some_experience', 'Some experience'), ('experienced', 'Experienced'), ('a_lot_of_experience', 'A lot of experience'), ('professional_expert', 'Professional expert')], default='none', max_length=30)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
