# Generated by Django 3.2.15 on 2022-09-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_experience_with_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimage',
            new_name='image',
        ),
    ]
