# Generated by Django 3.2.15 on 2022-09-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_experience_with_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience_with_cars',
        ),
    ]
