# Generated by Django 3.2.15 on 2022-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220918_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='city',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
