# Generated by Django 3.2.15 on 2022-09-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentlikes',
        ),
    ]
