# Generated by Django 3.2.15 on 2022-09-11 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('Alfa Romeo', 'Alfa Romeo'), ('Alpina', 'Alpina'), ('Aston Martin', 'Aston Martin')], default='none', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('model', models.CharField(max_length=200)),
                ('model_year', models.IntegerField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
