# Generated by Django 3.2.15 on 2022-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='brand',
            field=models.CharField(choices=[('Alfa Romeo', 'Alfa Romeo'), ('Alpina', 'Alpina'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Austin', 'Austin'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroën', 'Citroën'), ('Cupra', 'Cupra'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('DS', 'DS'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Isuzu', 'Isuzu'), ('Iveco', 'Iveco'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Lancia', 'Lancia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Maxus', 'Maxus'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mercury', 'Mercury'), ('MG', 'MG'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Oldsmobile', 'Oldsmobile'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Plymouth', 'Plymouth'), ('Polestar', 'Polestar'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Rover/BMC', 'Rover/BMC'), ('Saab', 'Saab'), ('SEAT', 'SEAT'), ('Skoda', 'Skoda'), ('Smart', 'Smart'), ('Ssang Yong', 'Ssang Yong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], default='none', max_length=30),
        ),
    ]
